<!DOCTYPE html>
	<html lang="en">
	<head>
	  <meta name="description" content="CSS vertical-align Property">
	  <meta name="keywords" content="css,css3,CSS vertical-align Property">
	  <meta name="author" content="webschooltoday.com">
    <title>CSS vertical-align Property - WebSchool Today</title>
 <?php include "../links.php" ?></head>
<body>
<div>
<div class="tital">CSS vertical-align Property</div>    
<?php include "../head_part.php" ?> 


    <div class="rg3-w clearfix"> 

<?php include "info_css_inner.php" ?>
        <div class="rg3-sec_main">
            <div class="rg3-sec_u">
                <div class="rg3-sec_i">
                    
</div>
                <h1>CSS <code>vertical-align</code> Property</h1>
                <p class="topic">Topic: <a href="stylel_properties.php">CSS3 Properties Reference</a><span class="topic-nav"><a href="style_unicode-bidi-property.php"><i class="fa fa-arrow-left" aria-hidden="true"></i></a><a href="style_visibility-property.php"><i class="fa fa-arrow-right" aria-hidden="true"></i></a></span></p>	
                <h2>Description</h2>
                <p>This <code>vertical-align</code> CSS property controls the vertical alignment of boxes generated by an <a href="../des-css/style_visual-formatting.php#inline-level">inline-level</a> element (usually text and images) with respect to the text baseline within a <a href="../des-css/style_visual-formatting.php#block-level">block-level</a> box, or of table cells within a row.</p>
                <p>The following table summarizes the usages context and the version history of this property.</p>
                <div class="shadow">
                    <table class="data description">
                        <tr>
                            <th>Default value:</th>
                            <td><code>baseline</code></td>
                        </tr>
                        <tr>
                            <th>Applies to:</th>
                            <td>Inline-level and table-cell elements</td>
                        </tr>
                        <tr>
                            <th>Inherited:</th>
                            <td>No</td>
                        </tr>
						<tr>
							<th>Animatable:</th>
							<td>Yes. <a href="style_animatable-properties.php"><i>See</i> <em>animatable properties</em></a>.</td>
						</tr>
                        <tr>
                            <th>Version:</th>
                            <td>CSS 1, 2, 3</td>
                        </tr>
                    </table>
                </div>	
                <hr />	
                <h2>Syntax</h2>
                <p>The syntax of the property is given with:</p>
                <div class="shadow">
                    <div class="syntax">
                        <table>
                            <tr>
                                <td><pre><span class="property">vertical-align</span>: </pre></td>
                                <td><span class="keyword">baseline</span> | <span class="keyword">sub</span> | <span class="keyword">super</span> | <span class="keyword">top</span> | <span class="keyword">text-top</span> | <span class="keyword">middle</span> | <span class="keyword">bottom</span> | <span class="keyword">text-bottom</span> | <i>length</i> | <i>percentage</i> | <a href="../definitions.php#initial">initial</a> | <a href="../definitions.php#inherit">inherit</a></td>
                            </tr>
                        </table>
                    </div>
                </div>
                <p>The example below shows the <code>vertical-align</code> property in action.</p>
                <div class="example">
                    <div class="my_codeb">
                        <div class="my_codeb-title"><h4>Example</h4><a href="../codelab8605.html" target="_blank" class="try-btn" title="Try this code using online Editor">Try this code <span>&raquo;</span></a></div>
                        <textarea id="code1">

img {
    vertical-align: middle;
}
span {
    vertical-align: super;
}
  </textarea>
	                            <script>
								var editor = CodeMirror.fromTextArea(document.getElementById("code1"), {
									mode: "text/html",
									tabMode: "indent",
									styleActiveLine: true,
									lineNumbers: true,
									lineWrapping: true
								});

							</script>
                    </div>
                </div>
                <hr />
                <h2>Property Values</h2>
                <p>The following table describes the values of this property.</p>
                <div class="shadow space">
                    <table class="data">
                        <tr>
                            <th style="width:85px;">Value</th>
                            <th>Description</th>
                        </tr>
                        <tr>
                            <td><code>baseline</code></td>
                            <td>Align the baseline of the element's box with the baseline of the parent box.</td>
                        </tr>
                        <tr>
                            <td><code>sub</code></td>
                            <td>Lower the baseline of the box to the position suitable for subscripts of the parent's box.</td>
                        </tr>
                        <tr>
                            <td><code>super</code></td>
                            <td>Raises the baseline of the box to the position suitable for superscripts of the parent's box.</td>
                        </tr>
                        <tr>
                            <td><code>top</code></td>
                            <td>Align the top of the element and its descendants with the top of the line box.</td>
                        </tr>
						<tr>
                            <td><code>text-top</code></td>
                            <td>Align the top of the element with the top of the parent element's font.</td>
                        </tr>
                        <tr>
                            <td><code>middle</code></td>
                            <td>Align the middle of the element with the point that's half the parent's <a href="../des-css/style_units.php">x-height</a> above the baseline of the parent box.</td>
                        </tr>
                        <tr>
                            <td><code>bottom</code></td>
                            <td>Align the bottom of the element and its descendants with the bottom of the line box.</td>
                        </tr>                        
                        <tr>
                            <td><code>text-bottom</code></td>
                            <td>Align the bottom of the element with the bottom of the parent element's font.</td>
                        </tr>
						<tr>
                            <td><i>length</i></td>
                            <td>A length value in <code>px</code>, <code>pt</code>, <code>cm</code>, <code>em</code>, etc. Length values raise (positive value) or lower (negative value) the box by this distance from the baseline of its parent. The value 0px is same as <code>baseline</code>.</td>
                        </tr>
                        <tr>
                            <td><i>percentage</i></td>
                            <td>Raise (positive value) or lower (negative value) the box by this distance (a percentage of the <code><a href="style_line-height-property.php">line-height</a></code> value). The value 0% is same as <code>baseline</code>.</td>
                        </tr>                        
						<tr>
							<td><code>initial</code></td>
							<td>Sets this property to its default value.</td>
						</tr>
                        <tr>
                            <td><code>inherit</code></td>
                            <td>If specified, the associated element takes the <a href="../definitions.php#computed-value">computed value</a> of its parent element <code>vertical-align</code> property.</td>
                        </tr>
                    </table>
                </div>
                <hr />
                <h2>Browser Compatibility</h2>
                <p>The <code>vertical-align</code> property is supported in all major modern browsers.</p>
                <div class="shadow">
                    <div class="support">
                        <table>
                            <tr>
                                <td><img src="../assets/images/browser.jpg" alt="Browsers Icon" /></td>
                                <td>
                                    <h2>Basic Support&mdash;</h2>
                                    <ul>
                                        <li>Firefox <span>1+</span></li>
                                        <li>Google Chrome <span>1+</span></li>
                                        <li>Internet Explorer <span>4+</span></li>
                                        <li>Apple Safari <span>1+</span></li>
                                        <li>Opera <span>4+</span></li>
                                    </ul>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
                <hr />
                <h2>Further Reading</h2>
                <p>See tutorial on: <a href="../des-css/style_alignment.php">CSS Alignment</a>.</p>
                <p>Related properties: <code><a href="style_line-height-property.php">line-height</a></code>.</p> 
                <div class="bottom-link clearfix">
                    <a href="style_unicode-bidi-property.php" class="previous-page-bottom"><i class="fa fa-arrow-left" aria-hidden="true"></i> Previous</a>
                    <a href="style_visibility-property.php" class="next-page-bottom" style="float: right;">Next <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
                    </div>
            </div>
        </div>        
        <div class="sidebar">
            
        </div>
    </div> 
</div>
	<?php include "../footer.php" ?>

</body>
</html>