<!DOCTYPE html>
	<html lang="en">
	<head>
	  <meta name="keywords" content="css,css3,Visual Formatting">
	  <meta name="author" content="webschooltoday.com">
    <title>Understanding CSS Visual Formatting - WebSchool Today</title>
    <meta name="description" content="Understanding CSS Visual Formatting" />
	 <?php include "../links.php" ?></head>
<body>
<div>
<div class="tital">Understanding CSS Visual Formatting</div>    
<?php include "../head_part.php" ?> 

    <div class="rg3-w clearfix"> 

<?php include "des-css.php" ?>
        <div class="rg3-sec_main">
            <div class="rg3-sec_u">
                <div class="rg3-sec_i">
                    
</div>
            <a href="style_units.php" class="previous-page" title="Go to Previous Page"><i class="fa fa-arrow-right" aria-hidden="true"></i></a>
            <a href="style_display.php" class="next-page" title="Go to Next Page"><i class="fa fa-arrow-right" aria-hidden="true"></i></a>
            <h1>CSS <span>Visual Formatting</span></h1>
            <p class="summary">The visual formatting model typically explains how elements in the document tree are processed for visual media such as computer screen.</p>
            <h2>CSS Visual Formatting Model</h2>
            <p>The CSS visual formatting model is the algorithm that is used to process the documents for visual media. In the visual formatting model, each element in the document tree generates zero or more boxes according to the <a href="style_box-model.php">box model</a>.</p>
            <p>The layout of these boxes is depends on the following factors:</p>
            <ul>
            	<li>box dimensions.</li>
                <li>type of the element (block or inline).</li>
                <li>positioning scheme (normal flow, <a href="style_float.php">float</a>, and <a href="style_position.php#absolute-positioning">absolute positioning</a>).</li>
                <li>relationships between elements in the <a href="../definitions.php#document-tree">document tree</a>.</li>
                <li>external information e.g. viewport size, built-in dimensions of images, etc.</li>
            </ul>
            <!--Note box-->
            <div class="color-box">
                <div class="shadow">
                    <div class="info-tab note-icon" title="Important Notes"><i></i></div>
                    <div class="note-box"  style="background-color:#ff8585">
                        <p><strong>Read Carefully:</strong> The document tree is the hierarchy of elements encoded in the source document. Every element in the document tree has exactly one parent, with the exception of the root element, which has none.</p>
                    </div>
                </div>
            </div>
            <!--End:Note box-->
            <hr />
            <h2>Type of Boxes Generated in CSS</h2>
            <p class="space">Every element displayed on a web page generates a rectangular box. The following section describes the types of boxes that may be generated by an element.</p>
            <h2 id="block-level">Block-level Elements and Block Boxes</h2>
            <p>Block-level elements are those elements that are formatted visually as blocks (i.e. takes up the full width available), with a line break before and after the element. For example, paragraph element (<a href="../info-html/html-p-tag.php"><code>&lt;p&gt;</code></a>), headings (<a href="../info-html/html-headings-tag.php"><code>&lt;h1&gt; to &lt;h6&gt;</code></a>), divisions (<a href="../info-html/html-div-tag.php"><code>&lt;div&gt;</code></a>) etc.</p>
            <p>Generally, block-level elements may contain inline elements and other block-level elements.</p>
            <hr />
            <h2 id="inline-level">Inline-level Elements and Inline Boxes</h2>
            <p>Inline-level elements are those elements of the source document that do not form new blocks of content; the content is distributed in lines. For example, emphasized pieces of text within a paragraph (<a href="../info-html/html-em-tag.php"><code>&lt;em&gt;</code></a>), spans (<a href="../info-html/html-span-tag.php"><code>&lt;span&gt;</code></a>), strong element (<a href="../info-html/html-strong-tag.php"><code>&lt;strong&gt;</code></a>) etc.</p>
            <p>Inline elements typically may only contain text and other inline elements.</p>
            <!--Note box-->
            <div class="color-box">
                <div class="shadow">
                    <div class="info-tab note-icon" title="Important Notes"><i></i></div>
                    <div class="note-box"  style="background-color:#ff8585">
                        <p><strong>Read Carefully:</strong> Unlike block-level elements, an inline-level element only takes up as much width as necessary, and does not force line breaks.</p>
                    </div>
                </div>
            </div>
            <!--End:Note box-->
            <p>You can change how an element will be displayed on a web page using the CSS display property. You will learn about the display property in <a href="style_display.php">next chapter</a>.</p>            
			<!--Bottom Navigation-->
            <div class="bottom-link clearfix">
                <a href="style_units.php" class="previous-page-bottom"><i class="fa fa-arrow-left" aria-hidden="true"></i> Previous</a>
                <a href="style_display.php" class="next-page-bottom">Next <i class="fa fa-arrow-right" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>        
        <div class="sidebar">
            
        </div>
    </div> 
</div>
	<?php include "../footer.php" ?>

</body>
</html>